### ISSUE TITLE
Please address crash-on-start issues on latest GPlay version!

### ISSUE THREAD

**Issue by TPS** [loisaidasam/mta-fare-buster-android#3]
You've some reviews to the effect, & I myself have sent a number of crash reports.

Thanks for the app!

**Comment by loisaidasam** [comment]
On it, thanks for the notice @TPS!

**Comment by TPS** [comment]
Anything else I can do to help?

**Comment by loisaidasam** [comment]
No thanks, I'm just migrating the project from Eclipse to Android Studio. Will keep you posted :)

**Comment by loisaidasam** [comment]
@TPS The app has been updated for Android Studio-style development.

I just pushed a build to the Play store - it might take a few hours to roll out, but once upgraded, this should fix any issues you're having.

Let me know :+1: :family:

**Comment by TPS** [comment]
Good job - only minor nit is not enough blank space left between number field & Go button, so it makes editing (specifically, putting cursor at field-end) difficult!

Thanks! ☺
